export const courses = [
  'Selecione o curso',
  'Não Estudo',
  'Administração',
  'Análise e Desenvolvimento de Sistemas',
  'Arquitetura',
  'Biomedicina',
  'Ciências Biológicas',
  'Ciências Contábeis',
  'Ciências Econômicas',
  'Ciência da Computação',
  'Direito',
  'Educação Física',
  'Enfermagem',
  'Engenharia Agrônoma',
  'Engenharia Civil',
  'Engenharia de Produção',
  'Engenharia Mecânica',
  'Farmácia',
  'Fisioterapia',
  'Medicina Veterinária',
  'Nutrição',
  'Pedagogia',
  'Psicologia',
  'Outro',
];